# Welcome to Jekyll!
#

# Site settings
title: Web Dev
description: |
  Professional Web Developers for Internet Innovations
owner: Web Dev # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: leandrorv26@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  github: https://github.com/leovazquez1
  linkedin-square: https://pr.linkedin.com/in/leandro-rios-294071115
  #twitter: https://twitter.com/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:
social2:
  github: https://github.com/waldemar-reyes
  linkedin-square: https://pr.linkedin.com/in/waldemar-reyes
  twitter: https://twitter.com/wally1713
  #facebook-official: https://facebook.com/wally1713


# Build settings
markdown: kramdown
#sass:
#  style: compressed
